Groups:
    Default:
        Default: false
        Distance: 0

    Whisper:
        Default: false
        Distance: 4

    Speak:
        Default: false
        Distance: 32

    Shout:
        Default: false
        Distance: 64

Messages:
    # Status
    Player_current_group_is: Player <player> current group is <group>.'
    Player_is_not_in_a_group: 'Player <player> is not in a group.'
    
    # Player status
    Your_current_group_is: 'Your current group is <group>.'
    You_are_not_in_a_group: 'You are not in a group.'
    
    # Join
    You_are_now_in_group: 'You are now in group <group>.'
    
    # Leave
    You_are_no_longer_in_a_group: 'You are no longer in a group.'
    
    # Create
    Group_succesfully_created: 'Group "<group>" succesfully created.'
    
    # Delete
    Group_successfully_deleted: 'Group "<group>" succesfully deleted.'
    
    # Spying
    You_are_now_spying: 'You are now spying.'
    You_are_no_longer_spying: 'You are no longer spying.'
    
    # Set
    Player_group_set_to: 'Player <player> chat group set to <group>.'
    
    # Does not exist messages
    Player_does_not_exist: 'Player does not exist.'
    Group_does_not_exist: 'Group does not exist.'
    World_does_not_exist: 'World does not exist.'
    
    # Already exists
    Group_already_exists: 'Group "<group>" already exists.'
    
    # Reload
    Reload_complete: 'Reload complete!'
    
    # Muted
    You_are_muted: 'You are muted.'